app/models.py
from . import db
from datetime import datetime

class User(db.Model):
    '''
    class holding users data
    '''
    id = db.Column(db.Integer, primary_key = True)
    username = db.Column(db.String(20), unique=True, nullable=False)
    email = db.Column(db.String(200), unique=True, nullable=False)
    password = db.Column(db.String(50), nullable=False)
    comments = db.relationship('Comment', backref='author', lazy=True)
    
    def __repr__(self):
        return f"User('{self.username}', '{self.email}')"

class Comment(db.Model):
    '''
    holding comments data for users
    '''
    id = db.Column(db.Integer, primary_key = True)
    content = db.Column(db.Text, nullable=False)
    date_posted = db.Column(db.DateTime, nullable=False, default = datetime.utcnow)
    title = db.Column(db.String, nullable=False)
    user_id = db.Column(db.Integer, db.ForeignKey('user.id'), nullable=False)
    
    def save_comment():
        '''
        function that adds,commits and saves comments for the user in the db
        '''
        db.session.add(self)
        db.session.commit()
        
        @classmethod
        def get_comment(cls,id):
            '''
            function that gets comment for a particular user 
            '''
            comments=Comment.query.filter_by(user_id=id).all()
            return comments
    
    def __repr__(self):
        return f"Comments('({self.title})', '{self.date_posted}')"

app/__init__.py
from flask import Flask
from flask_bootstrap import Bootstrap
from flask_sqlalchemy import SQLAlchemy
from config import Config
from flask_login import LoginManager
from config import config_options

login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'auth.login'

bootstrap = Bootstrap()
db = SQLAlchemy()

def create_app():
    app = Flask(__name__)
    
    app = Flask(__name__,instance_relative_config = True)
    app.config.from_object(Config)
    
    bootstrap.init_app(app)
    db.init_app(app)
    login_manager.init_app(app)
    
    db.init_app(app)
    
    from .main import main as main_blueprint
    app.register_blueprint(main_blueprint)
    
    from .auth import auth as auth_blueprint
    app.register_blueprint(auth_blueprint,url_prefix='/authenticate')
    
    
    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main',__name__)

from . import views

app/main/views.py
from flask import Flask, session
from flask import render_template,request,session,redirect,url_for,request
from . import main
from .. import db
from ..models import User, Comment
from flask_login import login_required, current_user
from .forms import commentform

app = Flask(__name__)
app.secret_key="super secret key"

@main.route('/')
def smartphones():
    '''
    route for the index page
    '''
    return render_template('index.html')


@main.route('/iphone')
def iphone():
    '''
    route that navigates to the iphone page
    '''
    return render_template('iphone.html')

@main.route('/sams')
def samsung():
    '''
    route that navigates to the samsung page
    '''
    return render_template('sams.html')


@main.route('/huawei')
def huawei():
    '''
    route that navigates to the huawei page 
    '''
    return render_template('huawei.html')

@main.route('/nokia')
def nokia():
    '''
    route that navigates to the nokia page 
    '''
    return render_template('nokia.html')   
        
@main.route('nokia/comments/<int:id>', methods='GET','POST')
@login_required
def comments(id):
    '''
    route that navigates to the comments page and enables users to comment
    '''
    form = commentform
    user_comment=User.filter_by(id=id).first
    
    if form.validate_on_submit():
            body=form.body.data
            
            new_comment=Comment(body=body, date_posted=date_posted)
            new_comment.save_comment()
            
            return redirect(url_for('.comments',id=id))
        
        comments=Comment.get_comments(id)
    return render_template('comments.html',comments=comments) 

app/templates/base.html
{% extends 'bootstrap/base.html'%}

{% block title %}Smartphones{% endblock title %}
<!-- Navbar block  --> 
{% block navbar %}
    {% include 'navbar.html' %}
{% endblock %}

app/templates/comments.html
{% extends 'base.html' %}

{% import 'bootstrap/wtf.html' as wtf %}

{% block styles %}
{{super()}}
{% endblock styles %}

{% block content %}

{% if comments %}
{% for comment in comments %}
<h5>comments</h5>
<p>{{comment.title}}</p>
<p>{{comment.content}}</p>
<p>{{comment.date_posted('%m%d%Y')}}</p>

{% endfor %}
{ else }
<p>there are no comments about this phone</p>
{% endif %}

{{wtf.quick_form(form)}}

{% endblock content %}

app/templates/huawei.html
{% extends 'base.html' %} 
{% block content %}

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static',filename='css/huawei.css')}}">
<script src="{{url_for('static', filename='js/huawei.js')}}"></script>

{% endblock styles %}

<h1>huawei</h1>

<div id="drag-container">
    <div id="spin-container">
       <img src="https://images.pexels.com/photos/206395/pexels-photo-206395.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" alt="">
       <img src="https://images.pexels.com/photos/1391498/pexels-photo-1391498.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" alt="">
       <img src="https://images.pexels.com/photos/1382731/pexels-photo-1382731.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" alt="">
       <img src="https://images.pexels.com/photos/1758144/pexels-photo-1758144.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" alt="">
       <img src="https://images.pexels.com/photos/1382734/pexels-photo-1382734.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" alt="">
       <img src="https://images.pexels.com/photos/1462636/pexels-photo-1462636.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" alt="">
       <a target="_blank" href="https://images.pexels.com/photos/139829/pexels-photo-139829.jpeg">
       <img src="https://images.pexels.com/photos/139829/pexels-photo-139829.jpeg?auto=compress&cs=tinysrgb&dpr=1&w=500" alt="">
       </a>
       <video controls autoplay="autoplay" loop>
          <source src="https://player.vimeo.com/external/322244668.sd.mp4?s=338c48ac2dfcb1d4c0689968b5baf94eee6ca0c1&profile_id=165&oauth2_token_id=57447761" type="video/mp4">
       </video>
       <p>3D Tiktok Carousel</p>
    </div>
    <div id="ground"></div>
 </div>
 <div id="music-container"></div>
{% endblock content %}

app/templates/index.html
{% extends 'base.html' %} 

{% block content %}
<h1>Competing Smartphones in the Generation</h1>
<div class="container">

  <!--start pictures slide-->
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <div class="carousel">
  <div id="logoCarousel" class="carousel slide" data-ride="carousel">
  <ol class="carousel-indicators black">
   <li data-target="#logoCarousel" data-slide-to="0" class="active"></li>
   <li data-target="#logoCarousel" data-slide-to="1"></li>
   <li data-target="#logoCarousel" data-slide-to="2"></li>
   <li data-target="#logoCarousel" data-slide-to="3"></li>
  </ol>
  
  <div class="carousel-inner">
   <div class="item active">
     <img src="https://dl.dropbox.com/s/ftbvmqlq5my7gwi/Foto%2009.12.17%2C%2021%2031%2018.jpg" style="width:100%">
     <div class="carousel-caption">
       <h3>Caption 1</h3>
     </div>
   </div>
  <!--where I started to duplicate for adding more pics to the slide-->
   <div class="item">
     <img src="https://dl.dropbox.com/s/a5h1kkkqx7h5ts9/Foto%2025.08.18%2C%2014%2037%2009.jpg" style="width:100%">
     <div class="carousel-caption">
       <h3>Caption 2</h3>
     </div>
   </div> <!--copied until here-->
   
  <div class="item">
     <img src="https://dl.dropbox.com/s/b8pxuaepuih10kn/Foto%2016.09.17%2C%2011%2033%2014.jpg?dl=0" style="width:100%">
     <div class="carousel-caption">
       <h3>Caption 3</h3>
     </div>
   </div>
   
   <div class="item">
     <img src="https://dl.dropbox.com/s/bk3wh0g1fmlff31/Foto%2026.08.18%2C%2000%2027%2046.jpg" style="width:100%">
     <div class="carousel-caption">
       <h3>Caption 4</h3>
     </div>
   </div>
   <!--end of duplicated lines-->
  <a class="left carousel-control" href="#logoCarousel" data-slide="prev">
   <span class="glyphicon glyphicon-chevron-left"></span>
  </a>
  <a class="right carousel-control" href="#logoCarousel" data-slide="next">
   <span class="glyphicon glyphicon-chevron-right"></span>
  </a>
  </div>
  </div>
  </div>
  <div class="row">
    <div class="col-md-4">
      <h2>IPHONE</h2>
      <img
        src="https://cdn.pixabay.com/photo/2018/01/08/02/34/technology-3068617__340.jpg"
        alt="" class="iphone" width="50%"
      />
      <a href="{{url_for('main.iphone')}}">view</a>
    </div>
    <div class="col-md-4">
      <h2>SAMSUNG</h2>
      <img
        src="https://cdn.pixabay.com/photo/2017/04/26/16/06/mobile-2262928__340.jpg"
        alt="" class="samsung" width="50%"
      />
      <a href="{{url_for('main.samsung')}}">view</a>
    </div>
    <div class="col-md-4">
      <h2>HUAWEI</h2>
      <img
        src="https://cdn.pixabay.com/photo/2017/12/22/15/55/technology-3033809__340.jpg"
        alt="" class="huawei" width="50%"
      />
      <a href="{{url_for('main.huawei')}}">view</a>
    </div>
    <div class="col-md-4">
      <h2>NOKIA</h2>
      <img
        src="https://cdn.pixabay.com/photo/2015/04/14/23/16/mobile-722946__340.jpg"
        alt="" class="nokia" width="50%"
      />
      <a href="{{url_for('main.nokia')}}">view</a>
    </div>
  </div>

</div>
{% endblock content %}

<style>

</style>

app/templates/iphone.html
{% extends 'base.html' %} 

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static',filename='css/iphone.css')}}">

{% endblock styles %}
{% block content %}

<h1>iphone</h1>

<div class="content-all">
    <div class="content-carrousel">
        <figure><img src="https://images.unsplash.com/photo-1519002020920-4ed7715eade3?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=500&q=60" height="100%"></figure>
        <figure><img src="https://cdn.pixabay.com/photo/2016/11/23/14/50/apple-1853337__340.jpg"></figure>
        <figure><img src="https://cdn.pixabay.com/photo/2015/03/01/11/29/mockup-654585__340.jpg"></figure>
        <figure><img src="https://cdn.pixabay.com/photo/2018/01/08/02/34/technology-3068617__340.jpg"></figure>
        <figure><img src="https://cdn.pixabay.com/photo/2017/04/23/23/52/phone-2255117__340.jpg"></figure>
        <figure><img src="https://cdn.pixabay.com/photo/2016/12/09/11/33/smartphone-1894723__340.jpg"></figure>
        <figure><img src="https://cdn.pixabay.com/photo/2016/02/10/16/39/girl-1192032__340.jpg"></figure>
        <figure><img src="https://cdn.pixabay.com/photo/2018/05/01/13/04/sport-3365503__340.jpg"></figure>
        <figure><img src="https://cdn.pixabay.com/photo/2016/10/11/09/26/office-1730939__340.jpg"></figure>
        <figure><img src="https://cdn.pixabay.com/photo/2016/11/29/05/08/apple-1867461__340.jpg"></figure>
    </div>
     
 </div>    
{% endblock content %}

app/templates/navbar.html
<nav class="navbar navbar-default">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">Smartphones</a>
    </div>
    <div id="navbar" class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li><a href="{{url_for('main.smartphones')}}">Home</a></li>
        <li><a href="{{url_for('auth.register')}}">Register</a></li>
      </ul>
    </div><!--/.nav-collapse -->
  </div>
</nav>

app/templates/nokia.html
{% extends 'base.html' %} 

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static',filename='css/nokia.css')}}">
<script src="{{url_for('static', filename='js/nokia.js')}}"></script>
{% endblock styles %}

{% block content %}

<h1>nokia</h1>

<base href="{{url_for('main.smartphones')}}">
<div id="carousel">
  <figure id="spinner">
    <img src="https://cdn.pixabay.com/photo/2015/02/04/15/23/nokia-623939__340.jpg" alt>
    <img src="https://cdn.pixabay.com/photo/2015/05/29/10/33/ux-789162__340.jpg" alt>
    <img src="https://cdn.pixabay.com/photo/2015/01/26/10/23/office-612532__340.jpg" alt>
    <img src="https://cdn.pixabay.com/photo/2015/09/06/00/50/nokia-926756__340.jpg" alt>
    <img src="https://cdn.pixabay.com/photo/2016/07/05/08/16/mobile-phone-1498271__340.jpg" alt>
    <img src="https://cdn.pixabay.com/photo/2015/08/08/01/41/nokia-879986__340.jpg" alt>
    <img src="https://cdn.pixabay.com/photo/2015/05/31/10/59/smartphone-791076__340.jpg" alt>
    <img src="https://cdn.pixabay.com/photo/2019/08/03/14/51/mobile-phone-4381895__340.jpg" alt>
  </figure>
</div>
<span style="float:left" class="ss-icon" onclick="galleryspin('-')">&lt;</span>
<span style="float:right" class="ss-icon" onclick="galleryspin('')">&gt;</span>

<div class="container">
  <h1>one</h1>
  <div class="col-md-6">
  <img src="https://cdn.pixabay.com/photo/2015/01/26/10/23/office-612532__340.jpg" alt="" width="">
</div>

<div class="col-md-6">
  <h1>two</h1>
  <img src="https://cdn.pixabay.com/photo/2015/04/14/23/16/mobile-722946__340.jpg" alt="" width="">
</div>

<div class="col-md-6">
  <h1>three</h1>
  <img src="https://cdn.pixabay.com/photo/2013/07/12/19/00/slider-154173__340.png" alt="" width="">
</div>

<div class="col-md-6">
  <h4>four</h4>
  <img src="https://cdn.pixabay.com/photo/2015/09/06/00/50/nokia-926756__340.jpg" alt="" width="">
  <a href="">comment</a>
</div>
</div>


{% endblock content %}
<style>

</style>

app/templates/sams.html
{% extends 'base.html' %} 

{% block styles %}
{{super()}}
<link rel="stylesheet" href="{{url_for('static',filename='css/sams.css')}}">
{% endblock styles %}

{% block content %}
<body>
    

<a href="#">
    <span></span>
    <span></span>
    <span></span>
    <span></span>
    Samsung
</a>
</body>
{% endblock content %}